title: The Scala Programming Language

scalaversion: "2.11.8"
devscalaversion: "2.12.0-RC1"

baseurl: ""
markdown: kramdown
exclude: [bundle-vendor]
future: true # necessary so that Jekyll even considers looking at posts with a date in the future (events)
